name: ielts_trainer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.0
  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0
  record: ^5.2.0
  # Для поиска путей на телефоне
  path_provider: ^2.1.2
  # Для запроса прав (микрофон)
  permission_handler: ^11.3.0

dependency_overrides:
  record_linux: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/audio/
    - assets/images/
  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/fonts/minecraft_0.ttf